title: Ravina Armiani
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  PZSIB
  <br><br>
  <a href="https://www.instagram.com/rvin_15/">View My Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
