title: Ravina Armiani
logo: "/images/IMG_20200525_201809.jpg?raw=true" 
description:
  PZSIB
  <br><br>
  Data Warehousing, Analysis, and Visualization for Business Insights
  <br><br>
  <a href="https://www.instagram.com/rvin_15/">View My Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
